import { enCatalog } from "../catalog";
import type { AppDictionary } from "../types";

export const enUS = {
    catalog: enCatalog,
    common: { loading: "Loading...", save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add", search: "Search", actions: "Actions", yes: "Yes", no: "No", confirm: "Confirm", close: "Close", view: "View", print: "Print", back: "Back", retry: "Try again" },
    auth: { login: "Sign in", logout: "Sign out", username: "Username", password: "Password", loginTitle: "Sign in to the system", loginError: "The username or password is incorrect.", sessionExpired: "Your session has expired. Please sign in again." },
    dashboard: { title: "Dashboard", dailySales: "Today's sales", totalProducts: "Total products", lowStock: "Low stock", expiringSoon: "Expiring soon", recentSales: "Recent sales", quickActions: "Quick actions", newSale: "New sale", addProduct: "Add product", viewReports: "View reports" },
    sales: { title: "Sales", invoices: "Invoices", invoiceNumber: "Invoice number", invoiceDate: "Invoice date", totalAmount: "Total amount", paymentType: "Payment type", cash: "Cash", credit: "Credit", customer: "Customer", addToInvoice: "Add to invoice", finishInvoice: "Complete invoice", currentInvoice: "Current invoice", invoiceHistory: "Invoice history", noItems: "No products found", selectProduct: "Select product", quantity: "Quantity", price: "Price", subtotal: "Subtotal", total: "Total", discount: "Discount", tax: "Tax", grandTotal: "Grand total" },
    inventory: { products: "Products", productName: "Product name", category: "Category", purchasePrice: "Purchase price", sellingPrice: "Selling price", stock: "Stock", unit: "Unit", barcode: "Barcode", description: "Description", addNewProduct: "Add new product", editProduct: "Edit product", productDetails: "Product details", lowStockAlert: "Low stock alert", expiryDate: "Expiry date" },
    procurement: { purchases: "Purchases", supplier: "Supplier", purchaseDate: "Purchase date", addNewPurchase: "Add new purchase", editPurchase: "Edit purchase", purchaseDetails: "Purchase details" },
    expenses: { title: "Expenses", category: "Expense category", amount: "Amount", date: "Date", description: "Description", addNew: "Add new expense", edit: "Edit expense", rent: "Rent", utilities: "Utilities", salaries: "Salaries", maintenance: "Maintenance", other: "Other" },
    users: { title: "Users", fullName: "Full name", role: "Role", admin: "Administrator", cashier: "Cashier", manager: "Manager", active: "Active", inactive: "Inactive", addNew: "Add new user", edit: "Edit user" },
    settings: { title: "Settings", storeInfo: "Store information", storeName: "Store name", storeAddress: "Address", storePhone: "Phone", storeEmail: "Email", taxNumber: "Tax number", invoiceSettings: "Invoice settings", accountSettings: "Account settings", changePassword: "Change password", currentPassword: "Current password", newPassword: "New password", confirmPassword: "Confirm password" },
    feedback: { saved: "Saved successfully.", deleted: "Deleted successfully.", added: "Added successfully.", updated: "Updated successfully.", errorOccurred: "An error occurred.", confirmDelete: "Are you sure you want to delete this item?", noData: "No data is available.", requiredField: "This field is required.", invalidInput: "The input is invalid.", unavailable: "This content is currently unavailable.", missingTranslation: "A safe default translation is being used for this content." },
    pagination: { previous: "Previous", next: "Next", page: "Page", of: "of", showing: "Showing", entries: "entries" },
    finance: { revenues: "Revenues", generalLedger: "General ledger", journalEntries: "Journal entries", trialBalance: "Trial balance", accountHistory: "Account history", chartOfAccounts: "Chart of accounts", journalVouchers: "Journal vouchers", debit: "Debit", credit: "Credit", balance: "Balance", account: "Account", reference: "Reference", notes: "Notes" },
    permissions: { rolesPermissions: "Roles and permissions", createRole: "Create new role", roleName: "Role name", permissions: "Permissions", module: "Module", canView: "View", canCreate: "Create", canEdit: "Edit", canDelete: "Delete" },
    sessions: { activeSessions: "Active sessions", device: "Device", ipAddress: "IP address", lastActivity: "Last activity", terminateSession: "Terminate session" },
    reports: { title: "Reports", sales: "Sales report", purchases: "Purchases report", inventory: "Inventory report", profit: "Profit report", exportPdf: "Export PDF", exportExcel: "Export Excel", exportCsv: "Export CSV", printSavePdf: "Print / Save PDF" },
    dates: { today: "Today", yesterday: "Yesterday", thisWeek: "This week", thisMonth: "This month", thisYear: "This year", from: "From", to: "To", range: "Date range" },
    units: { piece: "Piece", box: "Box", kilogram: "Kilogram", gram: "Gram", liter: "Liter", meter: "Meter" },
    analytics: { totalSales: "Total sales", totalExpenses: "Total expenses", totalRevenues: "Total revenues", totalAssets: "Total assets", todayExpenses: "Today's expenses", todayRevenues: "Today's revenues", lowStockAlerts: "Low stock alerts", expiringSoonAlerts: "Expiry alerts" },
    operations: { newRequest: "New request", purchaseRequests: "Purchase requests", deferredSales: "Deferred sales", creditCustomers: "Credit customers", auditTrail: "Audit trail", batchProcessing: "Batch processing" },
    messages: { itemsSelected: ({ count }) => `${count} item${count === 1 ? "" : "s"} selected`, recordsShown: ({ count, total }) => `Showing ${count} of ${total} records`, reportReady: ({ title }) => `${title} report is ready` },
    accessibility: { openMenu: "Open menu", closeDialog: "Close dialog", loadingContent: "Loading content", languageSelector: "Select language", currentLanguage: ({ language }) => `Current language: ${language}` },
} satisfies AppDictionary;
