<?php

namespace ApiDocEngine\Core;

use Symfony\Component\Yaml\Yaml;

class DocWriter
{
    private string $basePath;

    public function __construct(string $basePath)
    {
        $this->basePath = rtrim($basePath, '/');
    }

    public function write(string $domain, string $subDomain, array $openApiData): string
    {
        $dir  = "$this->basePath/$domain/$subDomain";
        $file = "$dir/open_api_doc.yaml";

        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $yaml = $this->toYaml($openApiData);
        file_put_contents($file, $yaml);

        return $file;
    }

    public function ensureStubExists(string $domain, string $subDomain): string
    {
        $dir  = "$this->basePath/$domain/$subDomain";
        $file = "$dir/open_api_doc.yaml";

        if (file_exists($file)) {
            return $file;
        }

        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $stub = [
            'openapi' => '3.0.3',
            'info'    => [
                'title'       => "$domain / $subDomain API",
                'version'     => '2.0.0',
                'description' => "API documentation for the $domain $subDomain sub-domain. No endpoints are currently registered in this sub-domain.",
            ],
            'servers' => [['url' => '/api/v2', 'description' => 'Production API v2']],
            'paths'   => new \stdClass(),
            'tags'    => [['name' => $subDomain, 'description' => "Endpoints for $domain $subDomain (no routes yet)"]],
            'components' => [
                'schemas' => [],
                'securitySchemes' => [
                    'SessionToken' => [
                        'type' => 'apiKey',
                        'in'   => 'header',
                        'name' => 'X-Session-Token',
                    ],
                ],
            ],
        ];

        file_put_contents($file, $this->toYaml($stub));

        return $file;
    }

    private function toYaml(array $data): string
    {
        $banner = implode("\n", [
            '# ============================================================',
            '# AUTO-GENERATED — DO NOT EDIT MANUALLY',
            '# Generated by: engines/api-doc-engine',
            '# Regenerate:   php artisan api-docs:generate',
            '# ============================================================',
            '',
        ]);

        $yaml = Yaml::dump(
            $this->prepareForYaml($data),
            inline: 10,
            indent: 2,
            flags: Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE
        );

        return $banner . $yaml;
    }

    private function prepareForYaml($value)
    {
        if ($value instanceof \stdClass) {
            return (array) $value;
        }
        if (is_array($value)) {
            $result = [];
            foreach ($value as $k => $v) {
                $result[$k] = $this->prepareForYaml($v);
            }
            return $result;
        }
        return $value;
    }
}
