[package]
name = "accore-desktop"
version = "0.1.0"
description = "Accore ERP desktop application"
authors = ["Accore ERP Contributors"]
license = "MIT"
repository = "https://github.com/Emran025/accore-erp"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[features]
default = []
server-product = []
client-product = []

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.0", features = [] }
tauri-plugin-log = "2"
base64 = "0.22"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
semver = { version = "1.0", features = ["serde"] }
sha2 = "0.10"
